[package]
name = "xterm-js-sys"
version = "0.1.0"
authors = ["Rahul Butani <rr.butani@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
crossterm = { git = "https://github.com/ut-utp/crossterm", version = "0.17.3" }
tui = { version = "0.9.1", default-features = false }
js-sys = "0.3.37"
wasm-bindgen = "0.2.60"
web-sys = "0.3.37"

[profile.release]
lto = true
