[package]
name = "xterm-js-sys"
version = "4.6.0-alpha1"
authors = ["Rahul Butani <r.r.butan.i+crates@gmail.com>"]
edition = "2021"

description = "Rust WebAssembly bindings for xterm.js."
homepage = "https://github.com/rrbutani/xterm-js-sys"
repository = "https://github.com/rrbutani/xterm-js-sys"

readme = "README.md"

keywords = ["xterm", "xtermjs", "tui-web", "tui", "terminal"]
categories = ["api-bindings", "command-line-interface", "external-ffi-bindings", "wasm", "web-programming"]

license = "MIT"

exclude = [".github"]

autoexamples = false


[badges]
github-actions = { repository = "rrbutani/xterm-js-sys", workflow = "full" }
# [TODO] # codecov = { repository = "rrbutani/xterm-js-sys", branch = "main", service = "github" }

is-it-maintained-issue-resolution = { repository = "rrbutani/xterm-js-sys" }
is-it-maintained-open-issues = { repository = "rrbutani/xterm-js-sys" }
maintenance = { status = "actively-developed" }


[lib]


[dependencies]
js-sys = "0.3.70"
wasm-bindgen = { version = "0.2.90", features = ["strict-macro"] }

log = { version = "0.4", optional = true }

[dependencies.web-sys]
version = "0.3.70"
features = [
    "Element",
    "HtmlTextAreaElement",
    "KeyboardEvent",
    "MouseEvent",
]


[dev-dependencies]
wasm-bindgen-test = "0.3.40"


[profile.release]
opt-level = 3
lto = true


[features]
default = ["ext"]
crossterm-support = []
ext = ["log"]


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown", "wasm32-wasip1"]
rustdoc-args = ["--cfg", "docs"]
all-features = true
default-target = "wasm32-unknown-unknown"


# Removed custom wasm-bindgen patch - using official releases now
