[workspace]
members = [
    "basic",
    "feature-showcase",
]


[profile.release]
lto = false # TODO: figure out why this introduces a bounds check on the with-input example when `= true`
debug = false


[patch.crates-io]
xterm-js-sys = { path = "../" }
