[workspace]
members = [
    "basic",
    "tui",
]


[profile.release]
lto = true
debug = true


[patch.crates-io]
wasm-bindgen = { git = "https://github.com/rrbutani/wasm-bindgen.git", branch = "patches" } # TODO: switch back once things get merged!
