on: [ push, pull_request ]

name: full

jobs:
  check:
    name: Check + test

    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.43.0
        target:
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown
          - wasm32-wasi

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true

      - name: Add wasm32-wasi target (needed to build bindgen)
        run: |
          rustup +${{ matrix.rust }} target install wasm32-wasi

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --all-features

      - name: Run cargo check release
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --all-features --release

      # We currently aren't set up to run tests on wasm:
      - name: Run cargo test
        if: env.target == x86_64-unknown-linux-gnu
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --no-fail-fast -- --include-ignored

      # We currently aren't set up to run tests on wasm:
      - name: Run cargo test release
        if: env.target == 'x86_64-unknown-linux-gnu'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --no-fail-fast --release -- --include-ignored

  lint:
    needs: check
    name: Format + run clippy

    strategy:
      fail-fast: false
      matrix:
        rust: [ stable, nightly ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
          target: wasm32-wasi

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings
